import type React from "react"

/** Shared inline styles for the config editor window and its tabs. */
export const styles: Record<string, React.CSSProperties> = {
  container: {
    display: "flex",
    flexDirection: "column",
    height: "100vh",
    background: "#1e1e1e",
    color: "#d4d4d4",
  },
  tabs: {
    display: "flex",
    borderBottom: "1px solid #333",
    background: "#252526",
    flexShrink: 0,
  },
  tab: {
    padding: "8px 16px",
    border: "none",
    background: "transparent",
    color: "#888",
    cursor: "pointer",
    fontSize: 13,
    fontFamily: "inherit",
    borderBottomWidth: 2,
    borderBottomStyle: "solid",
    borderBottomColor: "transparent",
  },
  tabActive: { color: "#fff", borderBottomColor: "#ff85a2" },
  toolbar: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    padding: "6px 10px",
    background: "#2d2d2d",
    borderBottom: "1px solid #333",
    flexShrink: 0,
  },
  btn: {
    padding: "4px 12px",
    border: "1px solid #555",
    borderRadius: 4,
    background: "#3c3c3c",
    color: "#d4d4d4",
    cursor: "pointer",
    fontSize: 12,
    fontFamily: "inherit",
  },
  btnDisabled: {
    opacity: 0.35,
    cursor: "not-allowed",
  },
  unsaved: { color: "#f0c040", fontSize: 12, marginLeft: 8 },
  err: { color: "#f44747", fontSize: 12, marginLeft: 8 },
  editor: { flex: 1, overflow: "hidden" },
  loading: {
    flex: 1,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: "#888",
  },

  // ── Env inspector ────────────────────────────────────────────────
  envWrap: { flex: 1, display: "flex", flexDirection: "column", overflow: "hidden" },
  envBar: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    padding: "6px 10px",
    background: "#2d2d2d",
    borderBottom: "1px solid #333",
    flexShrink: 0,
  },
  envFilter: {
    flex: 1,
    padding: "4px 8px",
    border: "1px solid #555",
    borderRadius: 4,
    background: "#1e1e1e",
    color: "#d4d4d4",
    fontSize: 12,
    fontFamily: "inherit",
    outline: "none",
  },
  envCount: { color: "#888", fontSize: 12, fontVariantNumeric: "tabular-nums" },
  envList: { flex: 1, overflow: "auto", padding: "4px 0" },
  envRow: {
    padding: "6px 12px",
    borderBottom: "1px solid #2a2a2a",
  },
  envHead: { display: "flex", alignItems: "center", gap: 8, marginBottom: 3 },
  envKey: {
    color: "#9cdcfe",
    fontSize: 12,
    fontWeight: 600,
    fontFamily: "Consolas, 'Cascadia Mono', monospace",
  },
  envBadge: {
    fontSize: 10,
    color: "#888",
    border: "1px solid #444",
    borderRadius: 8,
    padding: "0 6px",
    lineHeight: "14px",
  },
  envCopy: {
    marginLeft: "auto",
    border: "1px solid #444",
    borderRadius: 4,
    background: "#333",
    color: "#aaa",
    cursor: "pointer",
    fontSize: 11,
    lineHeight: "16px",
    padding: "0 6px",
    fontFamily: "inherit",
  },
  envValue: {
    color: "#ce9178",
    fontSize: 12,
    fontFamily: "Consolas, 'Cascadia Mono', monospace",
    wordBreak: "break-all",
    whiteSpace: "pre-wrap",
    cursor: "pointer",
  },
  envEmpty: { color: "#666", fontStyle: "italic" },
  envPaths: { listStyle: "none", margin: 0, padding: 0 },
  envPathItem: {
    display: "flex",
    alignItems: "baseline",
    gap: 8,
    padding: "1px 0",
  },
  envPathIdx: {
    color: "#666",
    fontSize: 10,
    minWidth: 22,
    textAlign: "right",
    fontVariantNumeric: "tabular-nums",
  },
  envPathText: {
    color: "#ce9178",
    fontSize: 12,
    fontFamily: "Consolas, 'Cascadia Mono', monospace",
    wordBreak: "break-all",
    cursor: "pointer",
  },
  envEmptyBox: { padding: 20, textAlign: "center", color: "#666", fontSize: 12 },
}
