[package]
name = "rcm-core"
version = "0.1.0"
edition = "2024"
license = "MIT"
description = "RCM core — system & API calls, types, and utilities"
authors = ["ahaoboy"]

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
which = { workspace = true }
trash = { workspace = true }
clipboard-rs = { workspace = true }
base64 = { workspace = true }
winreg = { workspace = true }
windows = { workspace = true }
regex = { workspace = true }
cmdexpand = { workspace = true }
dirs = { workspace = true }
rcm-com = { workspace = true }
easy-archive = { workspace = true }
tokio = { workspace = true, features = ["process"] }
ureq = { workspace = true }
autorun = { workspace = true }
quick-access = { workspace = true }
lnk-com = { workspace = true }
startmenu = { workspace = true }
upath = { workspace = true }
desktop-com = { workspace = true }
